<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body id="app">
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">

                <span class="navbar-text text-light">Dyxi MVP</span>
            </a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a
                            class="nav-link active"
                            aria-current="page"
                            href="<?= $this->url('home') ?>">Home
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://getlaminas.org/">Dyxi MVP</a> Orula Deviant
            </p>
        </footer>
    </div>
    <script>
        const app = Vue.createApp({
            data() {
                return {
                    message: 'Hello Vue!',
                    isDyslexic: true,
                }
            },

            methods: {
                showToast() {
                    this.$toast.open('This is a toast notification!');
                },

                toggleIsDyslexic() {
                    this.isDyslexic = !this.isDyslexic;
                },

                showAlert() {
                    Swal.fire('This is an alert!');
                },

                registerStudent() {
                    if (!this.$refs.studentName.value || !this.$refs.teacherId.value) {
                        Swal.fire('Please enter both student name and teacher ID');
                        return;
                    } else {
                        let formData = new FormData();
                        formData.append('studentName', this.$refs.studentName.value);
                        formData.append('studentAge', this.$refs.studentAge.value);
                        formData.append('teacherid', this.$refs.teacherId.value);
                        formData.append('isDyslexic', this.isDyslexic);

                        axios.post('/application/create-student', formData)
                            .then(response => {
                                if (response.status == 201) {
                                    Swal.fire({
                                        icon: 'success',
                                        title: 'Success!',
                                        text: response.data.message,
                                    }).then(() => {
                                        window.location.reload();
                                    });
                                } else {
                                    Swal.fire({
                                        icon: 'error',
                                        title: 'Oops...',
                                        text: err.response.data.message,

                                    });
                                }
                            })
                            .catch(error => {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Oops...',
                                    text: err.response.data.message,

                                });
                            });
                    }
                },

                registerTeacher() {
                    if (!this.$refs.teacherNameInput.value) {
                        Swal.fire('Please enter a teacher name');
                        return;
                    }
                    let formInput = new FormData();
                    formInput.append('teacherName', this.$refs.teacherNameInput.value);
                    axios.post('/application/create-teacher', formInput)
                        .then(response => {
                            if (response.status == 201) {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Success!',
                                    text: response.data.message,
                                }).then(() => {
                                    window.location.reload();
                                });
                            } else {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Oops...',
                                    text: "An error occured"
                                });
                            }
                        })
                        .catch(error => {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: "An error occured"
                            });
                        });
                }


            }


        }).mount('#app');
    </script>

    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
</body>

</html>