<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">DYXI MVP</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank">Laminas MVC Skeleton</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank">
        Check Laminas on GitHub &raquo;
    </a>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Register a teacher</h2>
            <div class="card-body">
               
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="<?php echo $this->url('application', ["action" => "register-teacher"]); ?>">Create Teacher &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Evaluate a child</h2>
            <div class="card-body">
               
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="<?php echo $this->url('application', ["action" => "register-student"]); ?>">Create Student &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Admin</h2>
            <div class="card-body">
                <p>
                    
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="<?php echo $this->url('admin', ["action" => "index"]); ?>">Admin &raquo;</a>
            </div>
        </div>
    </div>
</div>
