<form>
    <div class="mb-3">
        <label for="studentname" class="form-label">Student Name</label>
        <input type="text" ref="studentName" class="form-control" id="studentname" aria-describedby="studentHelp" placeholder="Enter student name">
        <div id="studentHelp" class="form-text">We'll never share your student name with anyone else.</div>
    </div>

    <div class="mb-3">
        <label for="studentage" class="form-label">Student Age</label>
        <input type="number" ref="studentAge" class="form-control" id="studentage" aria-describedby="studentHelp" placeholder="Enter student age">
        <div id="studentHelp" class="form-text">We'll never share your student age with anyone else.</div>
    </div>

    <div class="mb-3">
        <label for="teacherid" class="form-label">Teacher ID</label>
        <input type="text" ref="teacherId" class="form-control" id="teacherid" aria-describedby="teacherHelp" placeholder="Enter teacher ID">
        <div id="teacherHelp" class="form-text">We'll never share your teacher ID with anyone else.</div>
    </div>
    <div class="form-check">
        <input v-model="isDyslexic" @click="toggleIsDyslexic" class="form-check-input" type="checkbox" id="defaultCheck2">
        <label class="form-check-label" for="defaultCheck2">
           Child Is Possibly Dyslexic
        </label>
    </div>
    
    <button type="submit" @click.prevent="registerStudent" class="btn btn-primary">Submit</button>
</form>